Repository Gavalencia12/Mobile_Application, pull requests merged in 2024-10, with the labels that each got.

#17 15 new structure mvvm
  .idea/appInsightsSettings.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/carhive/CarHiveApplication.kt
  app/src/main/java/com/example/carhive/Data/datasource/local/SessionImpl.kt
  app/src/main/java/com/example/carhive/Data/datasource/local/UserRepositoryImpl.kt
  app/src/main/java/com/example/carhive/Data/datasource/remote/Firebase/FirebaseAuthDataSource.kt
  app/src/main/java/com/example/carhive/Data/datasource/remote/Firebase/FirebaseDatabaseDataSource.kt
  app/src/main/java/com/example/carhive/Data/datasource/remote/Firebase/FirebaseStorageDataSource.kt
  app/src/main/java/com/example/carhive/Data/datasource/remote/RepositoryImpl.kt
  app/src/main/java/com/example/carhive/Data/exception/RepositoryException.kt
  app/src/main/java/com/example/carhive/Data/mapper/UserMapper.kt
  app/src/main/java/com/example/carhive/Data/model/UserEntity.kt
  app/src/main/java/com/example/carhive/Data/repository/AuthRepository.kt
  app/src/main/java/com/example/carhive/Data/repository/SessionRepository.kt
  app/src/main/java/com/example/carhive/Data/repository/UserRepository.kt
  app/src/main/java/com/example/carhive/Domain/model/User.kt
  app/src/main/java/com/example/carhive/Domain/model/UserRole.kt
  app/src/main/java/com/example/carhive/Domain/usecase/auth/LoginUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/auth/RegisterUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/database/SaveUserToDatabaseUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/database/UploadToProfileImageUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/session/GetUserRoleUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/session/IsUserAuthenticatedUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/session/SaveUserRoleUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/user/ClearUserPreferencesUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/user/GetPasswordUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/user/GetUserPreferencesUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/user/SavePasswordUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/user/SaveUserPreferencesUseCase.kt
  app/src/main/java/com/example/carhive/MainActivity.kt
  app/src/main/java/com/example/carhive/Presentation/AuthViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/NavigationWrapper.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Login/LoginScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Login/view/LoginScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Login/viewModel/LoginViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/SecondSignupScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/ThirdSignupScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/FirstRegisterScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/SecondRegisterScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/ThirdRegisterScreen.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/viewModel/FirstRegisterViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/viewModel/SecondRegisterViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/viewModel/ThirdRegisterViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/seller/view/sellerScreen.kt
  app/src/main/java/com/example/carhive/Presentation/seller/viewModel/SellerViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/user/view/UserScreen.kt
  app/src/main/java/com/example/carhive/Presentation/user/viewModel/UserViewModel.kt
  app/src/main/java/com/example/carhive/di/AppModule.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: back-end

#26 Login and Register Design
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/config.properties
  .gradle/file-system.probe
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/color/checkbox_color_selector.xml
  app/src/main/res/drawable/ic_add_photo.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_arrow_next.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_phone.xml
  app/src/main/res/drawable/ic_recoverypass.png
  app/src/main/res/drawable/ic_register1.png
  app/src/main/res/drawable/ic_register2.png
  app/src/main/res/drawable/ic_register3.png
  app/src/main/res/drawable/ic_register4.gif
  app/src/main/res/drawable/ic_register5.png
  app/src/main/res/drawable/ic_visibility.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/rounded_cornes.xml
  app/src/main/res/drawable/rounded_edit_text.xml
  app/src/main/res/drawable/rounded_top_cornes.xml
  app/src/main/res/font/inter_bold.xml
  app/src/main/res/font/inter_extrabold.xml
  app/src/main/res/font/inter_semibold.xml
  app/src/main/res/font/kaushan_script.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_recovery_password.xml
  app/src/main/res/layout/fragment_register_first.xml
  app/src/main/res/layout/fragment_register_five.xml
  app/src/main/res/layout/fragment_register_fourth.xml
  app/src/main/res/layout/fragment_register_second.xml
  app/src/main/res/layout/fragment_register_third.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  gradle/libs.versions.toml
  local.properties
Labels: front-end

#27 Create View Admin
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/config.properties
  .gradle/file-system.probe
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/color/checkbox_color_selector.xml
  app/src/main/res/drawable/ic_add_photo.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_arrow_next.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_phone.xml
  app/src/main/res/drawable/ic_recoverypass.png
  app/src/main/res/drawable/ic_register1.png
  app/src/main/res/drawable/ic_register2.png
  app/src/main/res/drawable/ic_register3.png
  app/src/main/res/drawable/ic_register4.gif
  app/src/main/res/drawable/ic_register5.png
  app/src/main/res/drawable/ic_visibility.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/rounded_cornes.xml
  app/src/main/res/drawable/rounded_edit_text.xml
  app/src/main/res/drawable/rounded_top_cornes.xml
  app/src/main/res/font/inter_bold.xml
  app/src/main/res/font/inter_extrabold.xml
  app/src/main/res/font/inter_semibold.xml
  app/src/main/res/font/kaushan_script.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_recovery_password.xml
  app/src/main/res/layout/fragment_register_first.xml
  app/src/main/res/layout/fragment_register_five.xml
  app/src/main/res/layout/fragment_register_fourth.xml
  app/src/main/res/layout/fragment_register_second.xml
  app/src/main/res/layout/fragment_register_third.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  gradle/libs.versions.toml
  local.properties
Labels: front-end

#29 Profile view 3/4 final
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  app/src/main/java/com/example/carhive/MainActivity.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminHomeFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminHomeViewModel.kt
  app/src/main/res/drawable/bushines_man.png
  app/src/main/res/drawable/new_car.xml
  app/src/main/res/drawable/report.xml
  app/src/main/res/drawable/rounded_btn.xml
  app/src/main/res/drawable/rounded_option.xml
  app/src/main/res/drawable/rounded_profile.xml
  app/src/main/res/drawable/rounded_tag.xml
  app/src/main/res/drawable/rounder_baneos.xml
  app/src/main/res/drawable/rounder_information.xml
  app/src/main/res/drawable/rounder_security.xml
  app/src/main/res/drawable/user_history.xml
  app/src/main/res/drawable/user_new.xml
  app/src/main/res/drawable/warning.xml
  app/src/main/res/font/inter_light.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preloaded_fonts.xml
  gradle/libs.versions.toml
  local.properties
Labels: front-end

#30 Login and Registration Design Updates
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  app/src/main/java/com/example/carhive/MainActivity.kt
  app/src/main/res/drawable/btn_pulsado.xml
  app/src/main/res/drawable/ic_passw.xml
  app/src/main/res/drawable/rounded_cornes.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_recovery_password.xml
  app/src/main/res/layout/fragment_register_first.xml
  app/src/main/res/layout/fragment_register_five.xml
  app/src/main/res/layout/fragment_register_fourth.xml
  app/src/main/res/layout/fragment_register_second.xml
  app/src/main/res/layout/fragment_register_third.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  local.properties
Labels: front-end

#31 24 crud for the users in the admin section
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  app/build.gradle.kts
  app/src/main/java/com/example/carhive/Data/model/UserEntity.kt
  app/src/main/java/com/example/carhive/Data/model/UsuariosActivos.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/Adapters/UserAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/Adapters/UserAdapterBan.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminHomeFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminUserActiveFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminUserBanFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminUserListFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/UserDetailsDialogFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminUserActiveViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminUserBanViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminUserListViewModel.kt
  app/src/main/res/layout/fragment_admin_activate_user.xml
  app/src/main/res/layout/fragment_admin_ban_user_list.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/layout/fragment_admin_user_list.xml
  app/src/main/res/layout/fragment_user_details_dialog.xml
  app/src/main/res/layout/item_user.xml
  app/src/main/res/layout/item_user_ban.xml
  app/src/main/res/navigation/nav_graph.xml
  gradle/libs.versions.toml
  local.properties
Labels: back-end

#34 32 design of the ban interface and new users interface finish
  app/build.gradle.kts
  app/src/main/java/com/example/carhive/Data/model/UserEntity.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/Adapters/UserAdapterBan.kt
  app/src/main/res/drawable/rounded_corner_background.xml
  app/src/main/res/drawable/rounded_corner_background_gray.xml
  app/src/main/res/drawable/rounded_search.xml
  app/src/main/res/layout/fragment_admin_ban_user_list.xml
  app/src/main/res/layout/fragment_admin_user_list.xml
  app/src/main/res/layout/item_user.xml
  app/src/main/res/layout/item_user_ban.xml
  app/src/main/res/values/styles.xml
Labels: front-end

#36 Admin_Dashboard_Functionality
  app/build.gradle.kts
  app/src/main/java/com/example/carhive/Data/mapper/UserMapper.kt
  app/src/main/java/com/example/carhive/Data/model/UserEntity.kt
  app/src/main/java/com/example/carhive/Data/model/UsuariosActivos.kt
  app/src/main/java/com/example/carhive/Domain/model/User.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/Adapters/UserAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/Adapters/UserAdapterBan.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminHomeFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminUserActiveFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminUserBanFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/AdminUserListFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/view/UserDetailsDialogFragment.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminHomeViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminUserActiveViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminUserBanViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/admin/viewModel/AdminUserListViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/viewModel/ThirdRegisterViewModel.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/fragment_admin_activate_user.xml
  app/src/main/res/layout/fragment_admin_ban_user_list.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/layout/fragment_admin_user_list.xml
  app/src/main/res/layout/fragment_user_details_dialog.xml
  app/src/main/res/layout/item_user.xml
  app/src/main/res/layout/item_user_ban.xml
  app/src/main/res/navigation/nav_graph.xml
  settings.gradle.kts
Labels: back-end

#41 Enhancement of Login & Register Design and User Views
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/carhive/Presentation/initial/Login/view/LoginFragment.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/FirstRegisterFragment.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/SecondRegisterFragment.kt
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/ThirdRegisterFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/adapter/ImagePagerAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/user/view/ProfileFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/view/ProfileSellerFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/viewModel/ProfileViewModel.kt
  app/src/main/res/drawable/app_icon.xml
  app/src/main/res/drawable/btn_gray.xml
  app/src/main/res/drawable/btn_pulsado.xml
  app/src/main/res/drawable/btn_style.xml
  app/src/main/res/drawable/checkbox_heart_selector.xml
  app/src/main/res/drawable/circle_shape.xml
  app/src/main/res/drawable/ic_car_2.xml
  app/src/main/res/drawable/ic_change_account.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_heart_filled.xml
  app/src/main/res/drawable/ic_heart_outline.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_language.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/ic_mode_screen.xml
  app/src/main/res/drawable/ic_notifications.xml
  app/src/main/res/drawable/ic_person_outline.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_report_problem.xml
  app/src/main/res/drawable/ic_terms.xml
  app/src/main/res/drawable/ic_verified.xml
  app/src/main/res/drawable/ic_visibility_on.xml
  app/src/main/res/drawable/logo_bgb.png
  app/src/main/res/drawable/logo_bgw.png
  app/src/main/res/font/inter.xml
  app/src/main/res/layout/dialog_terms_seller_conditions.xml
  app/src/main/res/layout/dialog_terms_user_conditions.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_recovery_password.xml
  app/src/main/res/layout/fragment_register_first.xml
  app/src/main/res/layout/fragment_register_five.xml
  app/src/main/res/layout/fragment_register_fourth.xml
  app/src/main/res/layout/fragment_register_second.xml
  app/src/main/res/layout/fragment_register_third.xml
  app/src/main/res/layout/fragment_user_home.xml
  app/src/main/res/layout/fragment_user_home_cardetails.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/layout/fragment_user_profile_seller.xml
  app/src/main/res/layout/item_car.xml
  app/src/main/res/layout/item_car_favorites.xml
  app/src/main/res/layout/item_image.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
Labels: front-end

#43 40 create the splash screen and add the application logo
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/config.properties
  .gradle/file-system.probe
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/carhive/SplashActivity.kt
  app/src/main/res/drawable/car_hive_logo.webp
  app/src/main/res/drawable/logo.png
  app/src/main/res/layout/splash_screen.xml
  app/src/main/res/values/styles.xml
  gradle/libs.versions.toml
  local.properties
Labels: front-end

#46 Delete tracking files
  .gitignore
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/dependencies-accessors/gc.properties
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileChanges/last-build.bin
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/8.7/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/appInsightsSettings.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/other.xml
  .idea/studiobot.xml
  .idea/vcs.xml
  app/google-services.json
  local.properties
Labels: bug
