Repository Gavalencia12/Mobile_Application, pull requests merged in 2024-11, with the labels that each got.

#80 Filtrers ready, update attributes of car model and filter near of you ready
  app/build.gradle.kts
  app/src/main/java/com/example/carhive/Data/mapper/CarMapper.kt
  app/src/main/java/com/example/carhive/Data/model/CarEntity.kt
  app/src/main/java/com/example/carhive/Domain/model/Car.kt
  app/src/main/java/com/example/carhive/Presentation/seller/items/CrudDialogFragment.kt
  app/src/main/java/com/example/carhive/Presentation/seller/items/EditCarDialogFragment.kt
  app/src/main/java/com/example/carhive/Presentation/seller/viewModel/CarAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/seller/viewModel/CarFavoritesAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/seller/viewModel/CrudViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/seller/viewModel/DialogFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/adapter/BrandsAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/user/adapter/CarFavoritesAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/user/adapter/CarHomeAdapter.kt
  app/src/main/java/com/example/carhive/Presentation/user/items/CarDetailFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/view/FavoritesFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/view/UserHomeFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/viewModel/FavoritesViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/user/viewModel/UserViewModel.kt
  app/src/main/res/drawable/button_more_info_background.xml
  app/src/main/res/drawable/ic_person_outline.xml
  app/src/main/res/drawable/nav_options_background.xml
  app/src/main/res/layout/dialog_car_detail.xml
  app/src/main/res/layout/dialog_car_options.xml
  app/src/main/res/layout/dialog_edit_car.xml
  app/src/main/res/layout/dialog_filter.xml
  app/src/main/res/layout/fragment_seller_crud.xml
  app/src/main/res/layout/fragment_user_home.xml
  app/src/main/res/layout/fragment_user_home_cardetails.xml
  app/src/main/res/layout/item_brand.xml
  app/src/main/res/layout/item_car.xml
  app/src/main/res/layout/item_car_favorites.xml
  app/src/main/res/layout/item_seller_car.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle/libs.versions.toml
Labels: back-end

#81 Seller view redesign completed
  app/src/main/res/drawable/ic_review.png
  app/src/main/res/drawable/phone_call.png
  app/src/main/res/layout/fragment_seller_home.xml
  app/src/main/res/values/strings.xml
Labels: front-end

#82 SEARCH AND LOCATION READY
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/carhive/Presentation/seller/view/CarsListFragment.kt
  app/src/main/java/com/example/carhive/Presentation/seller/view/SellerCrudFragment.kt
  app/src/main/java/com/example/carhive/Presentation/seller/view/SellerFavoritesFragment.kt
  app/src/main/java/com/example/carhive/Presentation/seller/viewModel/CrudViewModel.kt
  app/src/main/java/com/example/carhive/Presentation/user/view/UserHomeFragment.kt
  app/src/main/java/com/example/carhive/Presentation/user/viewModel/UserViewModel.kt
  app/src/main/res/layout/dialog_filter.xml
  app/src/main/res/layout/fragment_cars_list.xml
  app/src/main/res/layout/fragment_seller_crud.xml
  app/src/main/res/layout/fragment_seller_favorites.xml
  app/src/main/res/layout/fragment_user_home.xml
  app/src/main/res/values/strings.xml
Labels: back-end

#83 Update architecture
  app/src/main/java/com/example/carhive/SplashActivity.kt
  app/src/main/res/drawable/button_create.xml
  app/src/main/res/drawable/button_delete.xml
  app/src/main/res/drawable/button_sign_out.xml
  app/src/main/res/drawable/ch_splash.gif
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_forward.xml
  app/src/main/res/drawable/rounded_btn.xml
  app/src/main/res/drawable/rounded_btn_exit.xml
  app/src/main/res/drawable/rounded_corner_background.xml
  app/src/main/res/drawable/rounded_option.xml
  app/src/main/res/drawable/rounded_profile.xml
  app/src/main/res/drawable/rounded_tag.xml
  app/src/main/res/drawable/rounder_baneos.xml
  app/src/main/res/drawable/rounder_information.xml
  app/src/main/res/drawable/spinner_background.xml
  app/src/main/res/font/roboto.xml
  app/src/main/res/layout/dialog_car_detail.xml
  app/src/main/res/layout/dialog_car_options.xml
  app/src/main/res/layout/dialog_confirm_delete.xml
  app/src/main/res/layout/dialog_edit_car.xml
  app/src/main/res/layout/fragment_admin_activate_user.xml
  app/src/main/res/layout/fragment_admin_ban_user_list.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/layout/fragment_admin_user_list.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_recovery_password.xml
  app/src/main/res/layout/fragment_register_first.xml
  app/src/main/res/layout/fragment_register_five.xml
  app/src/main/res/layout/fragment_register_fourth.xml
  app/src/main/res/layout/fragment_register_second.xml
  app/src/main/res/layout/fragment_register_third.xml
  app/src/main/res/layout/fragment_seller_crud.xml
  app/src/main/res/layout/fragment_seller_favorites.xml
  app/src/main/res/layout/fragment_seller_home.xml
  app/src/main/res/layout/fragment_seller_profile_terms.xml
  app/src/main/res/layout/fragment_user_favorites.xml
  app/src/main/res/layout/fragment_user_home.xml
  app/src/main/res/layout/fragment_user_home_cardetails.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/layout/fragment_user_profile_seller.xml
  app/src/main/res/layout/fragment_user_profile_terms.xml
  app/src/main/res/layout/item_car.xml
  app/src/main/res/layout/item_car_favorites.xml
  app/src/main/res/layout/item_car_image.xml
  app/src/main/res/layout/item_image.xml
  app/src/main/res/layout/item_selected_image.xml
  app/src/main/res/layout/item_seller_car.xml
  app/src/main/res/layout/item_user.xml
  app/src/main/res/layout/item_user_ban.xml
  app/src/main/res/layout/splash.xml
  app/src/main/res/layout/splash_screen.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: front-end

#85 Update register
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/carhive/Presentation/initial/Register/view/ThirdRegisterFragment.kt
  app/src/main/res/xml/file_paths.xml
Labels: back-end

#88 63 car acceptancerejection screen for the administrator
  app/src/main/java/com/example/carhive/presentation/admin/view/CarDetailDialogFragment.kt
  app/src/main/res/drawable/btn_dark_blue.xml
  app/src/main/res/layout/fragment_car_detail.xml
  app/src/main/res/layout/fragment_car_list.xml
  app/src/main/res/layout/item_admin_car.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: front-end

#89 Update Terms and Conditions and Add Privacy Policies
  app/src/main/java/com/example/carhive/presentation/initial/Register/view/SecondRegisterFragment.kt
  app/src/main/java/com/example/carhive/presentation/seller/view/SellerProfileFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/items/PrivacyPolicyFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/items/SellerPrivacyPolicyFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/items/TermsSellerFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/items/TermsUserFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/ProfileFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/ProfileSellerFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/viewModel/ProfileViewModel.kt
  app/src/main/res/drawable/ic_security_policy.xml
  app/src/main/res/layout/fragment_seller_profile_privacy_policy.xml
  app/src/main/res/layout/fragment_seller_profile_terms.xml
  app/src/main/res/layout/fragment_user_profile_privacy_policy.xml
  app/src/main/res/layout/fragment_user_profile_terms.xml
  app/src/main/res/layout/item_admin_car.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: front-end

#91 Add History for Administrator
  app/src/main/java/com/example/carhive/data/model/HistoryEntity.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/Adapters/HistoryAdapter.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminHistoryFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminHomeFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminUserBanFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/CarDetailDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/UserDetailsDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/viewModel/AdminHistoryViewModel.kt
  app/src/main/java/com/example/carhive/presentation/admin/viewModel/AdminUserBanViewModel.kt
  app/src/main/java/com/example/carhive/presentation/chat/viewModel/ChatViewModel.kt
  app/src/main/java/com/example/carhive/presentation/initial/Register/viewModel/FortRegisterViewModel.kt
  app/src/main/java/com/example/carhive/presentation/seller/view/CarsListFragment.kt
  app/src/main/java/com/example/carhive/presentation/seller/viewModel/CrudViewModel.kt
  app/src/main/java/com/example/carhive/presentation/seller/viewModel/SellerHomeViewModel.kt
  app/src/main/java/com/example/carhive/presentation/user/viewModel/UserViewModel.kt
  app/src/main/res/layout/fragment_admin_history.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/layout/item_admin_car.xml
  app/src/main/res/layout/item_history.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: back-end

#93 Fixed errors with the sending of technical support messages
  app/src/main/java/com/example/carhive/Domain/usecase/chats/SendFileMessageUseCase.kt
  app/src/main/java/com/example/carhive/data/datasource/remote/ChatRepositoryImpl.kt
  app/src/main/java/com/example/carhive/data/repository/ChatRepository.kt
  app/src/main/java/com/example/carhive/presentation/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/example/carhive/presentation/chat/view/ChatFragment.kt
  app/src/main/java/com/example/carhive/presentation/chat/viewModel/ChatViewModel.kt
  app/src/main/java/com/example/carhive/presentation/seller/view/SellerReportMessagesFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/UserReportMessagesFragment.kt
Labels: bug

#96 Bug admin
  app/src/main/java/com/example/carhive/presentation/admin/view/Adapters/UserAdapterBan.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminUserBanFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminUserListFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/UserDetailsDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/viewModel/AdminUserBanViewModel.kt
  app/src/main/java/com/example/carhive/presentation/admin/viewModel/AdminUserListViewModel.kt
  app/src/main/res/layout/item_user_ban.xml
  app/src/main/res/values/strings.xml
Labels: bug

#97 Redesign
  app/src/main/res/layout/fragment_user_details_dialog.xml
  app/src/main/res/layout/item_user.xml
  app/src/main/res/layout/item_user_ban.xml
Labels: front-end

#98 58 add notifications for vendors users and administrators
  app/build.gradle.kts
  app/src/main/java/com/example/carhive/CarHiveApplication.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/AddNotificationUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/ListenForCarApprovalStatusUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/ListenForChatMessagesUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/ListenForNewFavoritesUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/ListenForUserVerificationUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/MarkNotificationAsReadUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/NotifyCarApprovalStatusUseCase.kt
  app/src/main/java/com/example/carhive/Domain/usecase/notifications/ShowNotificationUseCase.kt
  app/src/main/java/com/example/carhive/MainActivity.kt
  app/src/main/java/com/example/carhive/data/datasource/remote/Firebase/FirebaseDatabaseDataSource.kt
  app/src/main/java/com/example/carhive/data/datasource/remote/NotificationsRepositoryImpl.kt
  app/src/main/java/com/example/carhive/data/model/NotificationModel.kt
  app/src/main/java/com/example/carhive/data/repository/NotificationsRepository.kt
  app/src/main/java/com/example/carhive/di/DataModule.kt
  app/src/main/java/com/example/carhive/di/DomainModule.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/Adapters/UserAdapterBan.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/CarDetailDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/UserDetailsDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/chat/view/ChatFragment.kt
  app/src/main/java/com/example/carhive/presentation/chat/viewModel/ChatViewModel.kt
  app/src/main/java/com/example/carhive/presentation/chat/viewModel/SellerInterestedUsersViewModel.kt
  app/src/main/java/com/example/carhive/presentation/notifications/adapter/NotificationsAdapter.kt
  app/src/main/java/com/example/carhive/presentation/notifications/adapter/NotificationsSellerAdapter.kt
  app/src/main/java/com/example/carhive/presentation/notifications/view/NotificationsFragment.kt
  app/src/main/java/com/example/carhive/presentation/notifications/view/NotificationsSellerFragment.kt
  app/src/main/java/com/example/carhive/presentation/notifications/viewModel/NotificationsViewModel.kt
  app/src/main/java/com/example/carhive/presentation/user/view/UserHomeFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/viewModel/UserViewModel.kt
  app/src/main/java/com/example/carhive/worker/UnreadMessagesWorker.kt
  app/src/main/res/drawable/ic_notification_car.xml
  app/src/main/res/drawable/ic_notification_chats.xml
  app/src/main/res/drawable/ic_notification_favorites.xml
  app/src/main/res/drawable/ic_notifications_account.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: back-end

#100 Enhancement of Register and Profile Edit Views, Filter Functionalities, and Colorful Button Implementation for Car Color Selection
  app/src/main/java/com/example/carhive/presentation/seller/items/CrudDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/seller/items/EditCarDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/seller/viewModel/CrudViewModel.kt
  app/src/main/java/com/example/carhive/presentation/user/items/UpdateDataDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/AdditionalDataFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/CarDetailFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/UserHomeFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/viewModel/UserViewModel.kt
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_photo.xml
  app/src/main/res/layout/dialog_car_options.xml
  app/src/main/res/layout/dialog_filter.xml
  app/src/main/res/layout/fragment_register_third.xml
  app/src/main/res/layout/fragment_update_data_dialog.xml
  app/src/main/res/layout/fragment_user_home_cardetails.xml
  app/src/main/res/values/strings.xml
Labels: back-end, front-end

#101 57 add vendor rating based on user experience
  app/src/main/java/com/example/carhive/data/model/RatingSellerEntity.kt
  app/src/main/java/com/example/carhive/presentation/seller/adapter/CommentHistoryAdapter.kt
  app/src/main/java/com/example/carhive/presentation/seller/adapter/CommentsAdapter.kt
  app/src/main/java/com/example/carhive/presentation/seller/view/SellerCommentHistoryFragment.kt
  app/src/main/java/com/example/carhive/presentation/seller/view/SellerHomeFragment.kt
  app/src/main/java/com/example/carhive/presentation/seller/view/SellerProfileFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/adapter/CarAdapter.kt
  app/src/main/java/com/example/carhive/presentation/user/adapter/CommentHistoryAdapter.kt
  app/src/main/java/com/example/carhive/presentation/user/adapter/RatingAdapter.kt
  app/src/main/java/com/example/carhive/presentation/user/items/TermsSellerFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/items/UserCommentDialog.kt
  app/src/main/java/com/example/carhive/presentation/user/view/CarDetailFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/ProfileFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/SellerProfileFragmentCars.kt
  app/src/main/java/com/example/carhive/presentation/user/view/UserCommentHistoryFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/view/UserSellerProfileCommentsFragment.kt
  app/src/main/java/com/example/carhive/presentation/user/viewModel/ProfileViewModel.kt
  app/src/main/res/drawable/border_style_price.xml
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/nostar.xml
  app/src/main/res/drawable/rounded_content_price.xml
  app/src/main/res/drawable/star.xml
  app/src/main/res/drawable/star_selector.xml
  app/src/main/res/drawable/starno.xml
  app/src/main/res/layout/dialog_user_comment.xml
  app/src/main/res/layout/fragment_seller_comment_history.xml
  app/src/main/res/layout/fragment_seller_home.xml
  app/src/main/res/layout/fragment_seller_profile_cars.xml
  app/src/main/res/layout/fragment_seller_profile_comments.xml
  app/src/main/res/layout/fragment_user_comment_history.xml
  app/src/main/res/layout/fragment_user_home_cardetails.xml
  app/src/main/res/layout/fragment_user_profile_comments.xml
  app/src/main/res/layout/item_car_seller.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_comments_seller.xml
  app/src/main/res/layout/item_user_ban.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: back-end, front-end

#105 Minor changes and fixed bugs
  app/src/main/java/com/example/carhive/data/model/MessageEntity.kt
  app/src/main/java/com/example/carhive/data/model/UserReport.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/Adapters/UserReportDetailsDialogFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/Adapters/UserReportsAdapter.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminHomeFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/view/AdminReportsFragment.kt
  app/src/main/java/com/example/carhive/presentation/admin/viewModel/AdminReportsViewModel.kt
  app/src/main/java/com/example/carhive/presentation/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/example/carhive/presentation/initial/Register/view/FortRegisterFragment.kt
  app/src/main/java/com/example/carhive/presentation/initial/Register/viewModel/FortRegisterViewModel.kt
  app/src/main/java/com/example/carhive/presentation/user/viewModel/UserViewModel.kt
  app/src/main/res/drawable/ic_reports_users.xml
  app/src/main/res/drawable/ic_support.xml
  app/src/main/res/layout/dialog_user_report_details.xml
  app/src/main/res/layout/fragment_admin_home.xml
  app/src/main/res/layout/fragment_admin_reports.xml
  app/src/main/res/layout/item_user_report.xml
  app/src/main/res/layout/message_item.xml
  app/src/main/res/layout/message_time.xml
  app/src/main/res/menu/chat_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: bug, back-end
